# Generated by Django 4.2.7 on 2024-01-12 03:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('did', models.AutoField(primary_key=True, serialize=False)),
                ('dname', models.CharField(max_length=150, verbose_name='Doctor Name')),
                ('dqua', models.CharField(max_length=255, verbose_name='Doctor Qualification')),
                ('aboutdoc', models.TextField(verbose_name='About Doctor')),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('sid', models.AutoField(primary_key=True, serialize=False)),
                ('days', models.CharField(max_length=200, verbose_name='Available Days')),
                ('t_slot', models.CharField(max_length=200)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.doctor', verbose_name='Select Doctor')),
            ],
        ),
    ]
